name: Foundry VTT Server Control

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Server action to perform'
        required: true
        default: 'status'
        type: choice
        options:
          - start
          - stop
          - status

jobs:
  control-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8'
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Create .env file
        run: |
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" > .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "EC2_INSTANCE_ID=${{ secrets.EC2_INSTANCE_ID }}" >> .env
          echo "DISCORD_TOKEN=dummy-token" >> .env
          echo "AUTHORIZED_USER_ID=dummy-id" >> .env
          
      - name: Run server command
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
        run: pnpm cli ${{ github.event.inputs.action }} 